require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Eurox' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  target 'EuroxTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Eurox-tvOS' do
  # Pods for Eurox-tvOS

  target 'Eurox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
